/**
 * Composes the full `align skill` markdown from the generated sections (rule kinds, DSL verbs,
 * bullet grammar, gates, CLI inventory — all read live from the installed binary, never
 * hand-written prose lists, Stage 5 IMPLEMENTATION_PLAN.md) and the static prose sections
 * (fix-loop protocol, doc-authoring guidance, baseline consent doctrine, MCP payload/tool
 * reference).
 */
import type { Command } from 'commander';
import { renderRuleKindsSection } from './rule-kinds.js';
import { renderDslVerbsSection } from './dsl-verbs.js';
import { renderBulletGrammarSection } from './bullet-grammar.js';
import { renderGatesSection } from './gates.js';
import { renderCliInventorySection } from './cli-inventory.js';
import { renderFixLoopProtocolSection, renderDocAuthoringSection, renderBaselineConsentSection, renderMcpPayloadReferenceSection, renderComponentSelectorSection } from './static-sections.js';

export type SkillTopic = 'authoring' | 'fixing' | 'all';

function section(heading: string, body: string): string {
  return `## ${heading}\n\n${body}`;
}

/** `program` is the already-built `commander` `Command` tree (`buildProgram()`, `../program.js`)
 * — passed in rather than imported here to avoid a cycle back to `program.ts`, which registers
 * the `skill` command that reaches this module (`cli-inventory.ts`'s doc comment has the full
 * rationale). */
export function renderSkillMarkdown(topic: SkillTopic, program: Command): string {
  const parts: string[] = [
    '# align — LLM skill guide',
    '',
    'align is an architecture-conformance verification oracle: a fluent TS DSL compiles to a portable JSON IR,',
    'a language plugin evaluates it against the real dependency graph on every call (always a fresh scan — no',
    'stale cache to distrust), and violations surface through the CLI and an MCP server. This guide is',
    'generated by `align skill` from the installed binary\'s own live registries — the rule-kind list, DSL verb',
    'table, bullet grammar, gate list, and CLI command inventory below can never drift from what this specific',
    'install actually supports.',
  ];

  if (topic === 'authoring' || topic === 'all') {
    parts.push(
      '',
      section(
        'Rule kinds',
        'Every rule kind the installed IR schema supports (walked live off `ruleIRSchema`):\n\n' + renderRuleKindsSection(),
      ),
      '',
      section('DSL verbs', 'The authoring surface (`defineProject`\'s `c.*` factories), introspected off the live builder objects:\n\n' + renderDslVerbsSection()),
      '',
      section('Component selectors: the glob dialect', renderComponentSelectorSection()),
      '',
      section(
        'Tier-2 bullet grammar (doc authoring)',
        'Sentence forms `- **Rule**: ...` bullets in an architecture doc parse into deterministically, zero LLM:\n\n' +
          renderBulletGrammarSection(),
      ),
      '',
      section('Doc authoring: the precision ladder', renderDocAuthoringSection()),
    );
  }

  if (topic === 'fixing' || topic === 'all') {
    parts.push('', section('Fix-loop protocol', renderFixLoopProtocolSection()), '', section('Baseline consent doctrine', renderBaselineConsentSection()), '', section('MCP payload & tool reference', renderMcpPayloadReferenceSection()));
  }

  parts.push('', section('Gates', renderGatesSection()), '', section('CLI commands', renderCliInventorySection(program)));

  return parts.join('\n');
}
