/**
 * The version stamp embedded in every `align skill --install`-written SKILL.md (`install.ts`): a
 * human-visible line plus a machine-parseable HTML-comment marker carrying the align version that
 * generated the snapshot.
 *
 * Why this exists: `align skill` (no `--install`) generates its guide live from the running
 * binary's own registries on every call, so it can never drift. `--install`, by contrast, writes a
 * point-in-time snapshot — a SKILL.md installed before some feature shipped (e.g. tier-2
 * `.because()` support) silently won't mention it, with nothing telling the human or agent the
 * snapshot is behind. The stamp makes that staleness detectable: `doctor.ts`'s `stale-skill`
 * advisory reads the marker back out of an installed file and compares it against the running
 * binary's `ALIGN_VERSION`. Defined here (not inline in `install.ts` or `doctor.ts`) so the
 * marker's exact format has exactly one source of truth shared between the writer and the reader.
 */

const VERSION_MARKER_PREFIX = 'align-skill-version';

/** Rendered into the installed body, near the top of the `<!-- align:start -->` block — never as
 * frontmatter, so it can't collide with the `name`/`description` keys a skill loader requires. */
export function renderVersionStamp(version: string): string {
  return (
    `> Generated by \`align skill\` v${version}. Re-run \`align skill --install\` after upgrading align to refresh this snapshot.\n` +
    `<!-- ${VERSION_MARKER_PREFIX}: ${version} -->`
  );
}

/** Extracts the stamped version from an installed SKILL.md's content, or `undefined` if the file
 * predates version stamping (no marker present) — the "missing marker" case `doctor.ts` treats as
 * stale on its own, distinct from a present-but-outdated version. */
export function parseSkillVersionMarker(content: string): string | undefined {
  const match = new RegExp(`<!--\\s*${VERSION_MARKER_PREFIX}:\\s*(\\S+)\\s*-->`).exec(content);
  return match?.[1];
}
