import type { DetectedComponent } from './detect-components.js';
import type { LayerSuggestion } from './suggest-layers.js';

/**
 * Renders the `align init` starter `align.config.ts`. Cycles-first (ADR 009: on the untouched,
 * architecturally-healthy kluster repo, cycle detection found two real latent bugs while every
 * `no-dependency` rule was green) — `arch.no-cycles()` ships active; the inferred layer
 * statements ship commented out ("~3 layer macros commented sensibly," IMPLEMENTATION_PLAN.md
 * Stage 1) since they're a suggestion a human should confirm, not a silently-enforced guess.
 *
 * `greenfieldComponents` (R4, greenfield mode, IMPLEMENTATION_PLAN.md Design Reserve): names of
 * detected components that matched zero files at probe-scan time (or every component, under
 * `align init --greenfield`) — rendered as `{ pattern, empty: 'until-populated' }` instead of the
 * plain string shorthand, so architecture-first authoring works out of the box: rules referencing
 * the component load immediately, `align check` shows it as ungrounded-but-green (R1) instead of a
 * load-time crash, and the empty-check auto-arms the moment real files land.
 */
export function renderConfig(
  components: readonly DetectedComponent[],
  layers: readonly LayerSuggestion[],
  greenfieldComponents: ReadonlySet<string> = new Set(),
): string {
  const componentLines = components
    .map((c) =>
      greenfieldComponents.has(c.name)
        ? `    ${JSON.stringify(c.name)}: { pattern: '${c.pattern}', empty: 'until-populated' }, // matched zero files at init time — architecture-first component, see the note above`
        : `    ${JSON.stringify(c.name)}: '${c.pattern}',`,
    )
    .join('\n');

  const layerLines = layers
    .map((l) => {
      const args = l.canDependOn.map((c) => `c.${c}`).join(', ');
      const line =
        l.canDependOn.length === 0
          ? `c.arch.component(c.${l.layer}).isIsolated()`
          : `c.arch.layer(c.${l.layer}).canOnlyDependOn(${args})`;
      return `    // ${l.evidence}.\n    // ${line},`;
    })
    .join('\n');

  const greenfieldNote =
    greenfieldComponents.size > 0
      ? `//\n// ${greenfieldComponents.size} component(s) below matched zero files when \`align init\` ran (architecture-first ` +
        `authoring — components declared before code exists). They're marked \`empty: 'until-populated'\`: ` +
        `\`align check\` treats them as provisionally green (surfaced distinctly, never silently), and the ` +
        `moment real files land under the selector the empty-check auto-arms — no manual flag flip needed. ` +
        `Run \`align doctor\` any time to see which ones are still empty vs. ready to have the marker removed.\n`
      : '';

  return `import { defineProject } from '@spikedpunch/align-core/dsl';

// Generated by \`align init\`. Components are auto-detected from your workspace layout — review
// the names/patterns below and adjust as needed; they're a starting point, not a final answer.
${greenfieldNote}export default defineProject({
  components: {
${componentLines}
  },
  rules: (c) => [
    // Cycles-first (align's day-one value, per real evidence: cycle detection finds latent bugs
    // on healthy repos far more often than dependency-direction rules do on first run).
    c.arch.noCycles(),

    // Suggested layering, inferred from today's measured cross-component edges. Uncomment the
    // ones that reflect your intended architecture — each is backed by the evidence noted above it.
${layerLines.length > 0 ? layerLines : '    // (not enough cross-component edges detected yet to suggest a layering)'}
  ],
});
`;
}
