import type { DetectedComponent } from './detect-components.js';
import type { LayerSuggestion } from './suggest-layers.js';

/**
 * Renders the `align init` starter `align.config.ts`. Cycles-first (ADR 009: on the untouched,
 * architecturally-healthy kluster repo, cycle detection found two real latent bugs while every
 * `no-dependency` rule was green) — `arch.no-cycles()` ships active; the inferred layer
 * statements ship commented out ("~3 layer macros commented sensibly," IMPLEMENTATION_PLAN.md
 * Stage 1) since they're a suggestion a human should confirm, not a silently-enforced guess.
 */
export function renderConfig(components: readonly DetectedComponent[], layers: readonly LayerSuggestion[]): string {
  const componentLines = components.map((c) => `    ${JSON.stringify(c.name)}: '${c.pattern}',`).join('\n');

  const layerLines = layers
    .map((l) => {
      const args = l.canDependOn.map((c) => `c.${c}`).join(', ');
      const line =
        l.canDependOn.length === 0
          ? `c.arch.component(c.${l.layer}).isIsolated()`
          : `c.arch.layer(c.${l.layer}).canOnlyDependOn(${args})`;
      return `    // ${l.evidence}.\n    // ${line},`;
    })
    .join('\n');

  return `import { defineProject } from '@align/core/dsl';

// Generated by \`align init\`. Components are auto-detected from your workspace layout — review
// the names/patterns below and adjust as needed; they're a starting point, not a final answer.
export default defineProject({
  components: {
${componentLines}
  },
  rules: (c) => [
    // Cycles-first (align's day-one value, per real evidence: cycle detection finds latent bugs
    // on healthy repos far more often than dependency-direction rules do on first run).
    c.arch.noCycles(),

    // Suggested layering, inferred from today's measured cross-component edges. Uncomment the
    // ones that reflect your intended architecture — each is backed by the evidence noted above it.
${layerLines.length > 0 ? layerLines : '    // (not enough cross-component edges detected yet to suggest a layering)'}
  ],
});
`;
}
